### ISSUE TITLE
Documents not creating...

### ISSUE THREAD

**Issue by sharmin-anee** [logzio/elasticsearch-stress-test#5]
# python elasticsearch-stress-test.py --es_address 139.0.0.1 128.0.0.2 --indices 4 --documents 5 --seconds 120 --not-green --clients 2

Test is done! Final results:
Elapsed time: 132 seconds
Successful bulks: 0 (0 documents)
Failed bulks: 26 (26000 documents)
Indexed approximately 0 MB which is 0.00 MB/s

Cleaning up created indices..  Done!

**Comment by roiravhon** [comment]
Can you please provide the output of:
curl 139.0.0.1:9200/_cluster/health
curl 128.0.0.2:9200/_cluster/health

Thanks,
Roi.

**Comment by sharmin-anee** [comment]
both health status is 'red' now.
But before testing the python script both health status were 'green'.

**Comment by roiravhon** [comment]
How many nodes are in each cluster?
They are both different clusters, right?

**Comment by sharmin-anee** [comment]
no, same cluster.
139.0.0.1 --> master node
139.0.0.2 --> client node

**Comment by roiravhon** [comment]
So that is the issue..
You should only place the client.
The ability to use multiple addresses is for different ES clusters.

Check all your red indices, delete them and run the script again using only one address (preferably the one of the client node).

Ill update the docs to better clarify the issue.

Please let me know if that worked out

**Comment by sharmin-anee** [comment]
Thanks, I'll inform you after testing.

**Comment by sharmin-anee** [comment]
Its working now.
Thank you

**Comment by roiravhon** [comment]
Awesome. Good day!

**Comment by sharmin-anee** [comment]
The cluster health status always remain 'red' after inserting

**Comment by roiravhon** [comment]
Can you please past the exact command you are running, 
And also the output of curl http://cluster:9200/_cat/indices before, and after the run.

Thanks

**Comment by sharmin-anee** [comment]
Before:

# curl http://$(curl ident.me):9200/_cat/indices?v  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

```
                             Dload  Upload   Total   Spent    Left  Speed
```

100    14    0    14    0     0     26      0 --:--:-- --:--:-- --:--:--    26
health status index pri rep docs.count docs.deleted store.size pri.store.size 

After:
 curl http://$(curl ident.me):9200/_cat/indices?v  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14    0    14    0     0     25      0 --:--:-- --:--:-- --:--:--    25
health status index          pri rep docs.count docs.deleted store.size pri.store.size 
red    open   hfpbtkluffey     3   1  
red    open   quaxpgkzqpcvte   3   1  
red    open   qn               3   1  
red    open   ydy              3   1

**Comment by roiravhon** [comment]
And the command you used to run?
Did you use the --no-cleanup flag?

What is your ES version and topology? (how many nodes from each type)
Any shard awareness configured?

**Comment by sharmin-anee** [comment]
### # python elasticsearch-stress-test.py --es_address XX.XX.XX.01 XX.XX.XX.02 --indices 4 --documents 5 --seconds 120 --no-cleanup --not-green --clients 2
- Elasticsearch version--2.3.3, and two nodes from each type
-  No shard awareness configured

**Comment by roiravhon** [comment]
Again, you are running the test on two nodes instead of one..

`python elasticsearch-stress-test.py --es_address XX.XX.XX.01 --indices 4 --documents 5 --seconds 120 --not-green --clients 2`

Only **one** node from each cluster should be in use.
And remove the --no-cleanup flag.. using it make the script not to cleanup after itself

**Comment by sharmin-anee** [comment]
I also tested it on one node, and same result found

**Comment by roiravhon** [comment]
one node, and without the --no-cleanup

Why are you closing the issue?

**Comment by sharmin-anee** [comment]
I've to work more on elastic-search version-2.3.3 then I'll test it.
Thanks for helping.

**Comment by roiravhon** [comment]
ok. LMK

**Comment by sharmin-anee** [comment]
Ok, Thank you.
